### ISSUE TITLE
Layout went wrong when you add a new peer

### ISSUE THREAD

**Issue by vtec83** [vpnhouse/tunnel#111]
If I fill in only the expiration date field and click save, then the error is not visible (i use browser Vivaldi)

![image](https://user-images.githubusercontent.com/12570996/197470858-2b3a2c83-73d4-4c87-bc8f-afb38e8338cc.png)

**Comment by un1tT** [comment]
@vtec83 thanks for the reporting! Fixed in https://github.com/vpnhouse/tunnel/pull/113.
